# gh issue create --title "make Command Connection Registration" --body "" --label "enhancement"
# gh issue create --title "make Command Password message" --body "" --label "enhancement"
# gh issue create --title "make Command Nick message" --body "" --label "enhancement"
# gh issue create --title "make Command User message" --body "" --label "enhancement"
# gh issue create --title "make Command Oper message" --body "" --label "enhancement"
# gh issue create --title "make Command User mode message" --body "" --label "enhancement"
# gh issue create --title "make Command Service message" --body "" --label "enhancement"
# gh issue create --title "make Command Quit" --body "" --label "enhancement"
# gh issue create --title "make Command Squit" --body "" --label "enhancement"
# 
# gh issue create --title "make Command Channel operations" --body "" --label "enhancement"
# gh issue create --title "make Command Join message" --body "" --label "enhancement"
# gh issue create --title "make Command Part message" --body "" --label "enhancement"
# gh issue create --title "make Command Channel mode message" --body "" --label "enhancement"
# gh issue create --title "make Command Topic message" --body "" --label "enhancement"
# gh issue create --title "make Command Names message" --body "" --label "enhancement"
# gh issue create --title "make Command List message" --body "" --label "enhancement"
# gh issue create --title "make Command Invite message" --body "" --label "enhancement"
# gh issue create --title "make Command Kick command" --body "" --label "enhancement"
# 
# gh issue create --title "make Command Sending messages" --body "" --label "enhancement"
# gh issue create --title "make Command Private messages" --body "" --label "enhancement"
# gh issue create --title "make Command Notice" --body "" --label "enhancement"
# 
# gh issue create --title "make Command Server queries and commands" --body "" --label "enhancement"
# gh issue create --title "make Command Motd message" --body "" --label "enhancement"
# gh issue create --title "make Command Lusers message" --body "" --label "enhancement"
# gh issue create --title "make Command Version message" --body "" --label "enhancement"
# gh issue create --title "make Command Stats message" --body "" --label "enhancement"
# gh issue create --title "make Command Links message" --body "" --label "enhancement"
# gh issue create --title "make Command Time message" --body "" --label "enhancement"
# gh issue create --title "make Command Connect message" --body "" --label "enhancement"
# gh issue create --title "make Command Trace message" --body "" --label "enhancement"
# gh issue create --title "make Command Admin command" --body "" --label "enhancement"
# gh issue create --title "make Command Info command" --body "" --label "enhancement"
# 
# gh issue create --title "make Command Service Query and Commands" --body "" --label "enhancement"
# gh issue create --title "make Command Servlist message" --body "" --label "enhancement"
# gh issue create --title "make Command Squery" --body "" --label "enhancement"
# 
# gh issue create --title "make Command User based queries" --body "" --label "enhancement"
# gh issue create --title "make Command Who query" --body "" --label "enhancement"
# gh issue create --title "make Command Whois query" --body "" --label "enhancement"
# gh issue create --title "make Command Whowas" --body "" --label "enhancement"
# 
# gh issue create --title "make Command Miscellaneous messages" --body "" --label "enhancement"
# gh issue create --title "make Command Kill message" --body "" --label "enhancement"
# gh issue create --title "make Command Ping message" --body "" --label "enhancement"
# gh issue create --title "make Command Pong message" --body "" --label "enhancement"
# gh issue create --title "make Command Error" --body "" --label "enhancement"
